---
- hosts: all
  become: true
  pre_tasks:
  roles:
  - base

- hosts: all
  become: true
  roles:
  - create_user

- hosts: webservers
  become: true
  roles:
  - create_webserver

- hosts: workstations
  become: true
  roles:
  - install_artifacts

- hosts: workstations
  become: true
  roles:
  - install_fileserver

- hosts: db_servers
  become: true
  roles:
  - db_servers


    



