---
# tasks file for create_webserver

- name: install apache and php for ubuntu servers
  tags: 'apache,apache2,ubuntu'
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == 'Ubuntu'
- name: install apache and php for centos servers
  tags: 'apache,centos,httpd'
  package:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == 'Rocky'
- name: start httpd
  tags: 'apache,centos,httpd'
  service:
    name: httpd
    state: started
    enabled: 'yes'
  when: ansible_distribution == 'Rocky'
- name: change email address for admin
  tags: 'apache,centos,httpd'
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: ^ServerAdmin
    line: ServerAdmin oktbabs@gmail.com
  when: ansible_distribution == 'Rocky'
  register: httpd
- name: restart httpd (Rocky)
  tags: 'apache,centos,httpd'
  service:
    name: httpd
    state: restarted
  when: httpd.changed
- name: Copy index files to webserver
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
